[package]
name = "tikv-client"
version = "0.0.0"
keywords = ["TiKV", "KV", "distributed-systems"]
license = "Apache-2.0"
authors = ["The TiKV Project Authors"]
repository = "https://github.com/tikv/client-rust"
description = "The rust language implementation of TiKV client."
edition = "2018"

[features]
default = []
# Enable integration tests with a running TiKV and PD instance.
# Use $PD_ADDRS, comma separated, to set the addresses the tests use. 
integration-tests = []

[lib]
name = "tikv_client"

[dependencies]
derive-new = "0.5"
failure = "0.1"
futures = { version = "0.3.5", features = ["async-await", "thread-pool"] }
futures-timer = "3.0"
grpcio = { version = "0.6", features = [ "secure", "prost-codec" ], default-features = false }
lazy_static = "1"
log = "0.4"
prometheus = { version = "0.8", features = [ "push", "process" ], default-features = false } 
rand = "0.7"
regex = "1"
serde = "1.0"
serde_derive = "1.0"
async-trait = "0.1"
tokio = { version = "0.2", features = ["sync"] }

tikv-client-common = { path = "tikv-client-common" }
tikv-client-pd = { path = "tikv-client-pd" }
tikv-client-proto = { path = "tikv-client-proto" }
tikv-client-store = { path = "tikv-client-store" }
mock-tikv = {path = "mock-tikv"}


[dev-dependencies]
clap = "2.32"
fail = { version = "0.3", features = [ "failpoints" ] }
proptest = "0.9"
proptest-derive = "0.1.0"
tempdir = "0.3"
serial_test = "0.5.0"
simple_logger = "1.9.0"
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }

[workspace]
members = [
    "tikv-client-common",
    "tikv-client-pd",
    "tikv-client-proto",
    "tikv-client-store",
    "mock-tikv"
]
