on:
  push:
    branches: [master]

name: Deploy rustdoc

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build docs
        run: cargo doc --document-private-items
       
      - name: sftp to server 
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'docclientftp'
          server: '161.35.234.130'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: 'target/doc/*'
          remote_path: '/var/www/tikv-dev/doc/rust-client'
          args: '-o ConnectTimeout=5' 
